apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocon22-app
  name: argocon22-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocon22-app
  template:
    metadata:
      labels:
        app: argocon22-app
    spec:
      containers:
        - image: ghcr.io/rcarrata/argocon22-app:v2
          imagePullPolicy: Always
          name: argocon22-app
          ports:
            - containerPort: 8080
              protocol: TCP
