apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocon22-app
  name: argocon22-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: argocon22-app